---
- name: "Install duplicacy"
  script: "install.sh duplicacy {{ duplicacy_path }} {{ install_duplicacy_version }}"
  args:
    creates: "{{ omit if install_duplicacy_force else duplicacy_path }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_path }}"
  when: install_duplicacy

- name: "Output duplicacy install path"
  debug:
    msg: "duplicacy{{ ' (forced)' if install_duplicacy_force else ''}} installed here: {{ duplicacy_path }}"
  when: install_duplicacy

- name: "Install duplicacy-util"
  script: "install.sh duplicacy-util {{ duplicacy_util_path }} {{ install_duplicacy_util_version }}"
  args:
    creates: "{{ omit if install_duplicacy_util_force else duplicacy_util_path }}"
  environment:
    PATH: "{{ ansible_env.PATH }}:{{ install_path }}"
  when: install_duplicacy_util

- name: "Output duplicacy-util install path"
  debug:
    msg: "duplicacy-util{{ ' (forced)' if install_duplicacy_util_force else ''}} installed here: {{ duplicacy_util_path }}"
  when: install_duplicacy_util

- name: Set duplicacy install facts
  set_fact:
    install_path: "{{ install_path }}"
    duplicacy_path: "{{ duplicacy_path }}"
    duplicacy_util_path: "{{ duplicacy_util_path }}"
