---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Executables are in path
      include_tasks: executable-in-path.yml
      loop:
        - duplicacy
        - "duplicacy-util"
