name: Release
"on":
  push:
    tags:
      - "*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and Deploy Collection
        uses: arillso/action.ansible.collection@1.0.3
        with:
          api_key: ${{ secrets.GALAXY_API_KEY }}
