---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-geerlingguy/docker-centos8-ansible:latest}"
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../../../resources/prepare.yml
    converge: ../../../resources/converge.yml
verifier:
  name: ansible
