---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../roles/${ROLE_NAME}/playbooks/converge.yml
    verify: ../roles/${ROLE_NAME}/playbooks/verify.yml
verifier:
  name: ansible
