---
- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: apt update
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: "Install bash, curl, jq"
      package:
        name:
          - bash
          - curl
          - jq
        state: present
