---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: local
provisioner:
  name: ansible
  playbooks:
    prepare: ../../../resources/prepare.yml
    converge: ../../../resources/converge.yml
verifier:
  name: ansible
